version: "3.7"

services:
    database:
        image: mongo:6.0.3
        ports:
          - "27017:27017"
    backend:
        build: 
          context: ./backend 
        restart: always
        depends_on:
            - database
        ports:
            - "5000:5000"
        networks:
            - clarusnet
    frontend:
        build: ./frontend/
        restart: always
        depends_on:
            - backend
        ports:
            - "3000:3000"
        networks:
            - clarusnet

networks:
    clarusnet:
        driver: bridge
