apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: res
  name: mern-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: res
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: res
    spec:
      containers:
      - image: jamesclarusway/mern-frontend
        name: frontend
        ports:
          - containerPort: 3000